<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <!-- base dimensions -->
    <xacro:property name="base_x_size" value="1.0" />
    <xacro:property name="base_y_size" value="0.65" />
    <xacro:property name="base_z_size" value="0.1" />

    <!-- wheel properties -->
    <xacro:property name="wheel_length" value="0.114" />
    <xacro:property name="wheel_radius" value="0.183" />

    <!-- material density -->
    <xacro:property name="base_density" value="1500.0" />
    <xacro:property name="wheel_density" value="400.0" />

    <!-- base and wheel mass -->
    <xacro:property name="base_mass" value="${base_density*base_x_size*base_y_size*base_z_size}" />
    <xacro:property name="wheel_mass" value="${wheel_density*pi*wheel_radius*wheel_radius*wheel_length}" />

    <!-- base link -->
    <link name="base_link">
    </link>

    <!-- base_footprint link -->
    <link name="base_footprint">
    </link>
    
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <!-- chassis -->
    <link name="chassis">
        <visual>
        <geometry>
            <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
        </geometry>
        <material name="white"/>
        </visual>
        <collision>
        <geometry>
            <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
        </geometry>
        </collision>
        <xacro:inertial_box mass="${base_mass}" x="${base_x_size}" y="${base_y_size}" z="${base_z_size}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 0"/>
    </joint>

    <gazebo reference="chassis">
        <material name="gazebo_white"/>
    </gazebo>

    <!-- wheels -->
    <xacro:macro name="wheel" params="prefix x_reflect y_reflect mu1 mu2">
        <link name="${prefix}_link">
            <visual>
                <geometry>
                    <cylinder length="${wheel_length}" radius="${wheel_radius}" />
                </geometry>
                <material name="blue"/>
            </visual>

            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}" />
                </geometry>
            </collision>
            <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
        </link>

        <joint name="${prefix}_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_link"/>
            <origin xyz="${x_reflect*(base_x_size/4)} ${y_reflect*(base_y_size + wheel_length)/2} 0" rpy="${-1*y_reflect*pi/2} 0 0"/>
            <axis xyz="0 0 ${y_reflect}"/>
        </joint>

        <gazebo reference="${prefix}_link">
            <material name="gazebo_blue"/>
            <mu1 value="${mu1}"/>
 <!--           <mu2 value="${mu2}"/> --> 
        </gazebo>
    </xacro:macro>

    <xacro:wheel prefix="front_left_wheel" x_reflect="1" y_reflect="1" mu1="0.0" mu2="0.0"/>
    <xacro:wheel prefix="front_right_wheel" x_reflect="1" y_reflect="-1" mu1="0.0" mu2="0.0"/>
    <xacro:wheel prefix="rear_left_wheel" x_reflect="-1" y_reflect="1" mu1="5.0" mu2="0.2"/>
    <xacro:wheel prefix="rear_right_wheel" x_reflect="-1" y_reflect="-1" mu1="5.0" mu2="0.2"/>

</robot>