controller_manager:
  ros__parameters:
    update_rate: 30 

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["front_left_wheel_joint", "rear_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "rear_right_wheel_joint"]

    wheel_separation: 0.1
    wheel_radius: 0.033

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    tf_frame_prefix_enable: false
    # open_loop: true